-- Supabase CRM schema for the AI Dental Voice Receptionist
-- Portfolio-safe schema: structure only; no credentials or patient data.

CREATE TABLE IF NOT EXISTS public."crm-system" (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    patient_name text,
    phone text,
    appointment_type text,
    appointment_date date,
    appointment_time text,
    timezone text,
    patient_type text,
    status text,
    source text,
    CONSTRAINT crm_system_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public."crm-system" IS
'CRM table for AI dental receptionist appointment intake and tracking';
